version: "3.8"

services:
  # 1. Node.js Backend Application
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/cryptopulse
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  # 2. MongoDB Container
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 3. Redis Container
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo-data:
